# Generated by Django 5.2.17 on 2026-09-09 22:14

from django.db import migrations, models


def backfill_allocations(apps, schema_editor):
    apps.get_model("orders", "OrderItem").objects.using(schema_editor.connection.alias).update(allocated_quantity=models.F("quantity"))


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0002_customization_frozen_at_customization_state'),
        ('orders', '0003_alter_order_payment_status_and_more'),
        ('products', '0008_oversized_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='allocated_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(backfill_allocations, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_quantity__lte', models.F('quantity'))), name='order_item_allocation_lte_quantity'),
        ),
    ]
