# Generated by Django 5.2.17 on 2026-09-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariant_active_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='garment_type',
            field=models.CharField(choices=[('tshirt', 'Remera'), ('oversized', 'Remera Oversize')], default='tshirt', max_length=16),
        ),
    ]
