# Generated by Django 5.2.17 on 2026-09-09 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_allocated_quantity_and_more'),
        ('products', '0008_oversized_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='garment_type',
            field=models.CharField(choices=[('hoodie', 'Hoodie'), ('tshirt', 'Remera'), ('oversized', 'Remera Oversize')], default='tshirt', max_length=16),
        ),
    ]
