# Generated by Django 5.2.17 on 2026-08-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_cart_item_per_variant',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customization_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='preview_back',
            field=models.ImageField(blank=True, null=True, upload_to='cart-previews/'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='preview_front',
            field=models.ImageField(blank=True, null=True, upload_to='cart-previews/'),
        ),
    ]
