# Generated by Django 5.2.17 on 2026-09-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_unique_cart_item_per_variant_and_more'),
        ('customizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='customization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart_items', to='customizations.customization'),
        ),
    ]
