# Generated by Django 5.2.17 on 2026-09-10 19:03

import django.db.models.deletion
import recommendations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('tagline', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='cultures/')),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DesignRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('garment_type', models.CharField(choices=[('hoodie', 'Hoodie'), ('tshirt', 'Remera'), ('oversized', 'Remera Oversize')], max_length=16)),
                ('preview_image', models.ImageField(upload_to=recommendations.models.recommendation_preview_path)),
                ('design_asset', models.ImageField(upload_to=recommendations.models.recommendation_asset_path)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('featured', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('default_position', models.JSONField(blank=True, default=dict)),
                ('default_scale', models.FloatField(default=1.0)),
                ('default_rotation', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommendations.culture')),
            ],
            options={
                'ordering': ['-featured', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['culture', 'garment_type', 'active'], name='recommendat_culture_bf145f_idx')],
            },
        ),
    ]
