# Generated by Django 5.2.17 on 2026-09-11 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_seed_cultures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='designrecommendation',
            options={'ordering': ['sort_order', '-featured', 'id']},
        ),
        migrations.AddField(
            model_name='designrecommendation',
            name='base_color',
            field=models.CharField(choices=[('Negro', 'Negro'), ('Blanco', 'Blanco'), ('Gris', 'Gris'), ('Azul', 'Azul'), ('Rojo', 'Rojo'), ('Verde', 'Verde')], default='Negro', max_length=16),
        ),
        migrations.AlterField(
            model_name='designrecommendation',
            name='default_rotation',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='designrecommendation',
            name='default_scale',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.35), django.core.validators.MaxValueValidator(2.5)]),
        ),
    ]
