# Generated by Django 5.2.17 on 2026-09-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_alter_designrecommendation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrecommendation',
            name='seed_key',
            field=models.CharField(blank=True, editable=False, max_length=80, null=True, unique=True),
        ),
    ]
