# Generated by Django 5.2.17 on 2026-09-11 21:38

import django.db.models.deletion
import recommendations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_designrecommendation_seed_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='designrecommendation',
            name='customization_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='designrecommendation',
            name='design_asset',
            field=models.ImageField(blank=True, upload_to=recommendations.models.recommendation_asset_path),
        ),
        migrations.CreateModel(
            name='RecommendationAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=recommendations.models.recommendation_layer_path)),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=50)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('file_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='recommendations.designrecommendation')),
            ],
        ),
    ]
