# Generated by Django 5.2.17 on 2026-09-02 19:08

from django.db import migrations, models


def mark_cart_customizations(apps, schema_editor):
    Customization = apps.get_model("customizations", "Customization")
    CartItem = apps.get_model("cart", "CartItem")
    customization_ids = CartItem.objects.exclude(customization_id=None).values_list("customization_id", flat=True)
    Customization.objects.filter(id__in=customization_ids).update(state="IN_CART")


def reset_customization_states(apps, schema_editor):
    apps.get_model("customizations", "Customization").objects.update(state="DRAFT")


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_customization'),
        ('customizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customization',
            name='state',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('IN_CART', 'En carrito'), ('ORDERED', 'Comprada')], db_index=True, default='DRAFT', max_length=16),
        ),
        migrations.RunPython(mark_cart_customizations, reset_customization_states),
    ]
