# Generated by Django 5.2.17 on 2026-09-15 17:15

import customizations.models
import customizations.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizations', '0002_customization_frozen_at_customization_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='private_assets',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customization',
            name='preview_back',
            field=models.ImageField(storage=customizations.storage.CustomizationStorage(), upload_to=customizations.models.customization_preview_path),
        ),
        migrations.AlterField(
            model_name='customization',
            name='preview_front',
            field=models.ImageField(storage=customizations.storage.CustomizationStorage(), upload_to=customizations.models.customization_preview_path),
        ),
        migrations.AlterField(
            model_name='customizationasset',
            name='file',
            field=models.ImageField(storage=customizations.storage.CustomizationStorage(), upload_to=customizations.models.customization_asset_path),
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(max_length=1000)),
                ('provider', models.CharField(max_length=80)),
                ('options', models.JSONField(default=dict)),
                ('file', models.ImageField(storage=customizations.storage.CustomizationStorage(), upload_to=customizations.models.generated_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved_design', to='customizations.customization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
    ]
